name: App Review Monitor

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC (1 AM PST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run App Review Monitor
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ISSUER_ID: ${{ secrets.ISSUER_ID }}
        KEY_ID: ${{ secrets.KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python app_review_monitor.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: app-review-monitor-logs
        path: logs/
        retention-days: 7 