name: App Review Monitor

on:
  schedule:
    # Run at 9am PST (16:00 UTC) every day
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # Debug installed packages
        
    - name: Verify environment variables
      run: |
        if [ -z "$APP_ID" ]; then echo "APP_ID is missing"; exit 1; fi
        if [ -z "$ISSUER_ID" ]; then echo "ASC_ISSUER_ID is missing"; exit 1; fi
        if [ -z "$KEY_ID" ]; then echo "ASC_KEY_ID is missing"; exit 1; fi
        if [ -z "$PRIVATE_KEY" ]; then echo "ASC_KEY_CONTENT is missing"; exit 1; fi
        if [ -z "$SLACK_WEBHOOK_URL" ]; then echo "SLACK_WEBHOOK_URL is missing"; exit 1; fi
        echo "All required environment variables are set"
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        KEY_ID: ${{ secrets.ASC_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.ASC_KEY_CONTENT }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Run App Review Monitor
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        KEY_ID: ${{ secrets.ASC_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.ASC_KEY_CONTENT }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "Starting app review monitor..."
        python -m app_review_monitor.cli --days 30 --debug
      continue-on-error: true 