name: App Review Monitor

on:
  schedule:
    # Run at 9am PST (16:00 UTC) every day
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run App Review Monitor
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        KEY_ID: ${{ secrets.ASC_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.ASC_KEY_CONTENT }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python -m app_review_monitor.cli --days 30 